
--Part – A

--1.Create a cursor Course_Cursor to fetch all rows from COURSE table and display them.
	
	DECLARE @SID INT,@SNAME VARCHAR(50),@SEMAIL VARCHAR(50),@SPHONE VARCHAR(50),@SDEPT VARCHAR(50),@SBDATE DATE,@SENROLL INT
	
	DECLARE COURSE_CURSOR CURSOR
	FOR
	SELECT StudentID,StuName,StuEmail,StuPhone,StuDepartment,StuDateOfBirth,StuEnrollmentYear FROM STUDENT
	OPEN COURSE_CURSOR
	FETCH NEXT FROM COURSE_CURSOR INTO @SID,@SNAME,@SEMAIL,@SPHONE,@SDEPT,@SBDATE,@SENROLL
	WHILE @@FETCH_STATUS=0
	BEGIN
		SELECT @SID,@SNAME,@SEMAIL,@SPHONE,@SDEPT,@SBDATE,@SENROLL
		FETCH NEXT FROM COURSE_CURSOR INTO @SID,@SNAME,@SEMAIL,@SPHONE,@SDEPT,@SBDATE,@SENROLL
	END
	CLOSE COURSE_CURSOR
	DEALLOCATE COURSE_CURSOR

--2. Create a cursor Student_Cursor_Fetch to fetch records in form of StudentID_StudentName (Example:
--1_Raj Patel).

	DECLARE @SID INT,@SNAME VARCHAR(50)
	
	DECLARE STUDENT_CURSOR CURSOR
	FOR
	SELECT StudentID,StuName FROM STUDENT
	OPEN STUDENT_CURSOR
	FETCH NEXT FROM STUDENT_CURSOR INTO @SID,@SNAME
	WHILE @@FETCH_STATUS=0
	BEGIN
		PRINT CAST(@SID AS VARCHAR(10))+'_' + @SNAME
		FETCH NEXT FROM STUDENT_CURSOR INTO @SID,@SNAME
	END
	CLOSE STUDENT_CURSOR
	DEALLOCATE STUDENT_CURSOR

--3. Create a cursor to find and display all courses with Credits greater than 3.

	DECLARE @CID VARCHAR(50),@CCREDITS INT
	
	DECLARE COURSE_CREDITS_CURSOR CURSOR
	FOR
	SELECT CourseID,CourseCredits FROM COURSE WHERE CourseCredits>3
	OPEN COURSE_CREDITS_CURSOR
	FETCH NEXT FROM COURSE_CREDITS_CURSOR INTO @CID,@CCREDITS
	WHILE @@FETCH_STATUS=0
	BEGIN
		PRINT @CID+'='+ CAST(@CCREDITS AS VARCHAR(10))
		FETCH NEXT FROM COURSE_CREDITS_CURSOR INTO @CID,@CCREDITS
	END
	CLOSE COURSE_CREDITS_CURSOR
	DEALLOCATE COURSE_CREDITS_CURSOR
	
--4. Create a cursor to display all students who enrolled in year 2021 or later.

	DECLARE @SID INT,@SNAME VARCHAR(50),@SENROLLY INT
	
	DECLARE STU_ENROLL_CURSOR CURSOR
	FOR
	SELECT StudentID,StuName,StuEnrollmentYear FROM STUDENT WHERE StuEnrollmentYear>=2021
	OPEN STU_ENROLL_CURSOR
	FETCH NEXT FROM STU_ENROLL_CURSOR INTO @SID,@SNAME,@SENROLLY
	WHILE @@FETCH_STATUS=0
	BEGIN
		PRINT CAST(@SID AS VARCHAR(10))+'='+@SNAME+','+ CAST(@SENROLLY AS VARCHAR(10))
		FETCH NEXT FROM STU_ENROLL_CURSOR INTO @SID,@SNAME,@SENROLLY
	END
	CLOSE STU_ENROLL_CURSOR
	DEALLOCATE STU_ENROLL_CURSOR
	
--5. Create a cursor Course_CursorUpdate that retrieves all courses and increases Credits by 1 for courses
--with Credits less than 4.

	DECLARE @CID VARCHAR(50),@CCREDITS INT
	
	DECLARE COURSE_CURSORUPDATE_CURSOR CURSOR
	FOR
	SELECT CourseID,CourseCredits FROM COURSE 
	OPEN COURSE_CURSORUPDATE_CURSOR
	FETCH NEXT FROM COURSE_CURSORUPDATE_CURSOR INTO @CID,@CCREDITS
	WHILE @@FETCH_STATUS=0
	BEGIN
		UPDATE COURSE SET CourseCredits=CourseCredits + 1 WHERE CourseID=@CID
		FETCH NEXT FROM COURSE_CURSORUPDATE_CURSOR INTO @CID,@CCREDITS
	END
	CLOSE COURSE_CURSORUPDATE_CURSOR
	DEALLOCATE COURSE_CURSORUPDATE_CURSOR

--6. Create a Cursor to fetch Student Name with Course Name (Example: Raj Patel is enrolled in Database
--Management System)

	DECLARE @SNAME VARCHAR(50),@CNAME VARCHAR(50)
	
	DECLARE STU_FETCH_CURSOR CURSOR
	FOR
	SELECT StuName,CourseName 
	FROM ENROLLMENT JOIN STUDENT
	ON ENROLLMENT.StudentID=STUDENT.StudentID
	JOIN COURSE
	ON ENROLLMENT.CourseID=COURSE.CourseID
	OPEN STU_FETCH_CURSOR
	FETCH NEXT FROM STU_FETCH_CURSOR INTO @SNAME,@CNAME
	WHILE @@FETCH_STATUS=0
	BEGIN
		PRINT @SNAME + ' is enrolled in ' + @CNAME
		FETCH NEXT FROM STU_FETCH_CURSOR INTO @SNAME,@CNAME
	END
	CLOSE STU_FETCH_CURSOR
	DEALLOCATE STU_FETCH_CURSOR

--7. Create a cursor to insert data into new table if student belong to ‘CSE’ department. (create new table
--CSEStudent with relevant columns)

	CREATE TABLE CSEStudent(
		SID INT,
		SNAME VARCHAR(50),
		SDEPT VARCHAR(50)
	)

	DECLARE @SID INT,@SNAME VARCHAR(50),@SDEPT VARCHAR(50)
	
	DECLARE STU_INSERT_CURSOR CURSOR
	FOR
	SELECT StudentID,StuName,StuDepartment FROM STUDENT WHERE StuDepartment='CSE'
	OPEN STU_INSERT_CURSOR
	FETCH NEXT FROM STU_INSERT_CURSOR INTO @SID,@SNAME,@SDEPT
	WHILE @@FETCH_STATUS=0
	BEGIN
		INSERT INTO CSEStudent VALUES (@SID,@SNAME,@SDEPT)
		FETCH NEXT FROM STU_INSERT_CURSOR INTO @SID,@SNAME,@SDEPT
	END
	CLOSE STU_INSERT_CURSOR
	DEALLOCATE STU_INSERT_CURSOR

	SELECT * FROM CSEStudent

--Part – B

--8. Create a cursor to update all NULL grades to 'F' for enrollments with Status 'Completed'

	DECLARE 
		@ENROLLMENTID INT,
		@GRADE VARCHAR(2)

	DECLARE ENROLLMENT_UPDATE_CURSOR CURSOR
	FOR
	SELECT ENROLLMENTID,ENROLLMENTSTATUS
		   GRADE
	FROM ENROLLMENT
	WHERE ENROLLMENTSTATUS = 'COMPLETED'

	OPEN ENROLLMENT_UPDATE_CURSOR

	FETCH NEXT FROM ENROLLMENT_UPDATE_CURSOR
	INTO @ENROLLMENTID,
		 @GRADE

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF @GRADE IS NULL
		BEGIN
			UPDATE ENROLLMENT
			SET GRADE = 'F'
			WHERE ENROLLMENTID = @ENROLLMENTID
		END

		FETCH NEXT FROM ENROLLMENT_UPDATE_CURSOR
		INTO @ENROLLMENTID,
			 @GRADE
	END

	CLOSE ENROLLMENT_UPDATE_CURSOR
	DEALLOCATE ENROLLMENT_UPDATE_CURSOR

--9. Cursor to show Faculty with Course they teach (EX: Dr. Sheth teaches Data structure)
	DECLARE 
		@FACULTYNAME VARCHAR(100),
		@COURSENAME VARCHAR(100)

	DECLARE FACULTY_COURSE_CURSOR CURSOR
	FOR
	SELECT F.FACULTYNAME, C.COURSENAME
	FROM FACULTY F
	JOIN COURSE FC ON F.FACULTYID = F.FACULTYID
	JOIN COURSE C ON FC.COURSEID = C.COURSEID

	OPEN FACULTY_COURSE_CURSOR

	FETCH NEXT FROM FACULTY_COURSE_CURSOR
	INTO @FACULTYNAME, @COURSENAME

	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT @FACULTYNAME + ' TEACHES ' + @COURSENAME

		FETCH NEXT FROM FACULTY_COURSE_CURSOR
		INTO @FACULTYNAME, @COURSENAME
	END

	CLOSE FACULTY_COURSE_CURSOR
	DEALLOCATE FACULTY_COURSE_CURSOR

--Part – C

--10. Cursor to calculate total credits per student (Example: Raj Patel has total credits = 15)
	DECLARE 
		@STUDENTID INT,
		@STUNAME VARCHAR(100),
		@TOTALCREDITS INT

	DECLARE STUDENT_CREDIT_CURSOR CURSOR
	FOR
	SELECT S.STUDENTID,
		   S.STUNAME,
		   SUM(C.COURSECREDITS)
	FROM STUDENT S
	JOIN ENROLLMENT E ON S.STUDENTID = E.STUDENTID
	JOIN COURSE C ON E.COURSEID = C.COURSEID
	GROUP BY S.STUDENTID,S.STUNAME

	OPEN STUDENT_CREDIT_CURSOR

	FETCH NEXT FROM STUDENT_CREDIT_CURSOR
	INTO @STUDENTID,
		 @STUNAME,
		 @TOTALCREDITS

	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT @STUNAME + ' HAS TOTAL CREDITS = ' + CAST(@TOTALCREDITS AS VARCHAR)

		FETCH NEXT FROM STUDENT_CREDIT_CURSOR
		INTO @STUDENTID,
			 @STUNAME,
			 @TOTALCREDITS
	END

	CLOSE STUDENT_CREDIT_CURSOR
	DEALLOCATE STUDENT_CREDIT_CURSOR	
